# Generated by Django 4.1.7 on 2023-03-13 18:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the company')),
                ('website', models.URLField(blank=True, verbose_name='Website of the company')),
                ('city', models.CharField(default='Unknown', max_length=100, verbose_name='City of the company')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='The email address is not valid.')], verbose_name='Email address of the company')),
                ('physical_address', models.CharField(blank=True, max_length=100, verbose_name='Physical address of the company')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Name of the contact person')),
                ('job_listing_site', models.URLField(blank=True, verbose_name='Job listing website')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('job_site', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_favorite', models.BooleanField(default=False)),
                ('job_link', models.CharField(default='', max_length=255)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_ads', to='annuaire.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.ManyToManyField(blank=True, to='annuaire.note', verbose_name='Notes about the company'),
        ),
    ]
