# Generated by Django 4.1.7 on 2023-03-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobad',
            options={'ordering': ['-date_added']},
        ),
    ]
