# Generated by Django 4.1.7 on 2023-02-23 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de la personne à contacter'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message="L'adresse email n'est pas valide.")], verbose_name="Adresse email de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_listing_site',
            field=models.URLField(blank=True, verbose_name="Site web des offres d'emploi"),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.ManyToManyField(blank=True, to='annuaire.note', verbose_name="Notes sur l'entreprise"),
        ),
        migrations.AlterField(
            model_name='company',
            name='physical_address',
            field=models.CharField(blank=True, max_length=100, verbose_name="Adresse physique de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name="Site web de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(verbose_name='Texte de la note'),
        ),
    ]
