# Generated by Django 4.1.7 on 2023-03-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0002_alter_jobad_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job_listing_site',
        ),
    ]
