# Generated by Django 4.1.7 on 2023-02-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0003_company_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='notes',
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.CharField(blank=True, max_length=500, verbose_name="Notes sur l'entreprise"),
        ),
    ]
