# Generated by Django 4.1.7 on 2023-03-11 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0004_remove_company_notes_company_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='City of the company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name of the contact person'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='The email address is not valid.')], verbose_name='Email address of the company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_listing_site',
            field=models.URLField(blank=True, verbose_name='Job listing website'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of the company'),
        ),
        migrations.RemoveField(
            model_name='company',
            name='notes',
        ),
        migrations.AlterField(
            model_name='company',
            name='physical_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Physical address of the company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website of the company'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_favorite', models.BooleanField(default=False)),
                ('job_link', models.CharField(default='', max_length=255)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuaire.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.ManyToManyField(blank=True, to='annuaire.note', verbose_name='Notes about the company'),
        ),
    ]
